<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container40zCYeY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container40zCYeY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container40zCYeY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container40zCYeY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container40zCYeY\App_KernelDevDebugContainer([
    'container.build_hash' => '40zCYeY',
    'container.build_id' => '8f81d1d5',
    'container.build_time' => 1682680501,
], __DIR__.\DIRECTORY_SEPARATOR.'Container40zCYeY');
