<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_chauffeur_index_back' => [[], ['_controller' => 'App\\Controller\\ChauffeurController::indexback'], [], [['text', '/chauffeur/back']], [], [], []],
    'app_chauffeur_new_back' => [[], ['_controller' => 'App\\Controller\\ChauffeurController::newback'], [], [['text', '/chauffeur/back/new']], [], [], []],
    'app_chauffeur_show_back' => [['id'], ['_controller' => 'App\\Controller\\ChauffeurController::showback'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chauffeur/back']], [], [], []],
    'app_chauffeur_edit_back' => [['id'], ['_controller' => 'App\\Controller\\ChauffeurController::editback'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/chauffeur/back']], [], [], []],
    'app_chauffeur_delete' => [['id'], ['_controller' => 'App\\Controller\\ChauffeurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chauffeur']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/admin']], [], [], []],
    'app_chauffeur_statistics' => [[], ['_controller' => 'App\\Controller\\InfoTrafficChauffeurController::index'], [], [['text', '/chauffeur/statistics']], [], [], []],
    'app_infotrafic_index' => [[], ['_controller' => 'App\\Controller\\InfotraficController::index'], [], [['text', '/infotrafic/']], [], [], []],
    'app_infotrafic_index_back' => [[], ['_controller' => 'App\\Controller\\InfotraficController::indexback'], [], [['text', '/infotrafic/back']], [], [], []],
    'app_infotrafic_new' => [[], ['_controller' => 'App\\Controller\\InfotraficController::new'], [], [['text', '/infotrafic/new']], [], [], []],
    'app_infotrafic_new_back' => [[], ['_controller' => 'App\\Controller\\InfotraficController::newback'], [], [['text', '/infotrafic/back/new']], [], [], []],
    'app_infotrafic_show' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic']], [], [], []],
    'app_infotrafic_show_back' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::showback'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic/back']], [], [], []],
    'app_infotrafic_edit' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic']], [], [], []],
    'app_infotrafic_edit_back' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::editback'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic/back']], [], [], []],
    'app_infotrafic_delete' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic']], [], [], []],
    'app_infotrafic_delete_back' => [['id'], ['_controller' => 'App\\Controller\\InfotraficController::deleteback'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/infotrafic/back']], [], [], []],
    'app_infotraffic_like' => [['infoid'], ['_controller' => 'App\\Controller\\InfotraficController::like'], [], [['text', '/like'], ['variable', '/', '[^/]++', 'infoid', true], ['text', '/infotrafic/infotraffic']], [], [], []],
    'app_infotraffic_dislike' => [['infoid'], ['_controller' => 'App\\Controller\\InfotraficController::dislike'], [], [['text', '/dislike'], ['variable', '/', '[^/]++', 'infoid', true], ['text', '/infotrafic/infotraffic']], [], [], []],
    'ajax_search' => [[], ['_controller' => 'App\\Controller\\InfotraficController::chercherInfotrafic'], [], [['text', '/infotrafic/ajax_search/']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
