<?php

namespace ContainerGVHJfJv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TDmlSVsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TDmlSVs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TDmlSVs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'infotrafic' => ['privates', '.errored..service_locator.TDmlSVs.App\\Entity\\Infotrafic', NULL, 'Cannot autowire service ".service_locator.TDmlSVs": it references class "App\\Entity\\Infotrafic" but no such service exists.'],
        ], [
            'infotrafic' => 'App\\Entity\\Infotrafic',
        ]);
    }
}
