<?php

namespace ContainerGVHJfJv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2UsoMVVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2UsoMVV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2UsoMVV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ChauffeurController::delete' => ['privates', '.service_locator.qmTBU0T', 'get_ServiceLocator_QmTBU0TService', true],
            'App\\Controller\\ChauffeurController::editback' => ['privates', '.service_locator.qmTBU0T', 'get_ServiceLocator_QmTBU0TService', true],
            'App\\Controller\\ChauffeurController::indexback' => ['privates', '.service_locator.jx4Da1f', 'get_ServiceLocator_Jx4Da1fService', true],
            'App\\Controller\\ChauffeurController::newback' => ['privates', '.service_locator.jx4Da1f', 'get_ServiceLocator_Jx4Da1fService', true],
            'App\\Controller\\ChauffeurController::showback' => ['privates', '.service_locator.Ef8xEl6', 'get_ServiceLocator_Ef8xEl6Service', true],
            'App\\Controller\\InfotraficController::delete' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController::deleteback' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController::edit' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController::editback' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController::index' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController::indexback' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController::new' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController::newback' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController::show' => ['privates', '.service_locator.TDmlSVs', 'get_ServiceLocator_TDmlSVsService', true],
            'App\\Controller\\InfotraficController::showback' => ['privates', '.service_locator.TDmlSVs', 'get_ServiceLocator_TDmlSVsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ChauffeurController:delete' => ['privates', '.service_locator.qmTBU0T', 'get_ServiceLocator_QmTBU0TService', true],
            'App\\Controller\\ChauffeurController:editback' => ['privates', '.service_locator.qmTBU0T', 'get_ServiceLocator_QmTBU0TService', true],
            'App\\Controller\\ChauffeurController:indexback' => ['privates', '.service_locator.jx4Da1f', 'get_ServiceLocator_Jx4Da1fService', true],
            'App\\Controller\\ChauffeurController:newback' => ['privates', '.service_locator.jx4Da1f', 'get_ServiceLocator_Jx4Da1fService', true],
            'App\\Controller\\ChauffeurController:showback' => ['privates', '.service_locator.Ef8xEl6', 'get_ServiceLocator_Ef8xEl6Service', true],
            'App\\Controller\\InfotraficController:delete' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController:deleteback' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController:edit' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController:editback' => ['privates', '.service_locator.nE6w.4.', 'get_ServiceLocator_NE6w_4_Service', true],
            'App\\Controller\\InfotraficController:index' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController:indexback' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController:new' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController:newback' => ['privates', '.service_locator.zGydyVQ', 'get_ServiceLocator_ZGydyVQService', true],
            'App\\Controller\\InfotraficController:show' => ['privates', '.service_locator.TDmlSVs', 'get_ServiceLocator_TDmlSVsService', true],
            'App\\Controller\\InfotraficController:showback' => ['privates', '.service_locator.TDmlSVs', 'get_ServiceLocator_TDmlSVsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ChauffeurController::delete' => '?',
            'App\\Controller\\ChauffeurController::editback' => '?',
            'App\\Controller\\ChauffeurController::indexback' => '?',
            'App\\Controller\\ChauffeurController::newback' => '?',
            'App\\Controller\\ChauffeurController::showback' => '?',
            'App\\Controller\\InfotraficController::delete' => '?',
            'App\\Controller\\InfotraficController::deleteback' => '?',
            'App\\Controller\\InfotraficController::edit' => '?',
            'App\\Controller\\InfotraficController::editback' => '?',
            'App\\Controller\\InfotraficController::index' => '?',
            'App\\Controller\\InfotraficController::indexback' => '?',
            'App\\Controller\\InfotraficController::new' => '?',
            'App\\Controller\\InfotraficController::newback' => '?',
            'App\\Controller\\InfotraficController::show' => '?',
            'App\\Controller\\InfotraficController::showback' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ChauffeurController:delete' => '?',
            'App\\Controller\\ChauffeurController:editback' => '?',
            'App\\Controller\\ChauffeurController:indexback' => '?',
            'App\\Controller\\ChauffeurController:newback' => '?',
            'App\\Controller\\ChauffeurController:showback' => '?',
            'App\\Controller\\InfotraficController:delete' => '?',
            'App\\Controller\\InfotraficController:deleteback' => '?',
            'App\\Controller\\InfotraficController:edit' => '?',
            'App\\Controller\\InfotraficController:editback' => '?',
            'App\\Controller\\InfotraficController:index' => '?',
            'App\\Controller\\InfotraficController:indexback' => '?',
            'App\\Controller\\InfotraficController:new' => '?',
            'App\\Controller\\InfotraficController:newback' => '?',
            'App\\Controller\\InfotraficController:show' => '?',
            'App\\Controller\\InfotraficController:showback' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
