# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    #security.password_encoder:
        #class: Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
        #arguments: ['%kernel.secret%']
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    knp_snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments:
            - '%env(WKHTMLTOPDF_PATH)%'
            # You may need to modify the path to the wkhtmltopdf binary as necessary.
            - []
# Windows configuration
knp_snappy:
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary: '%env(WKHTMLTOPDF_PATH)%'
        options:    
           
           no-outline: true
           page-size: LETTER
           encoding: UTF-8

    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
