<?php

namespace ContainerXgjGAzv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rr0Rj6BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rr0Rj6B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rr0Rj6B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chauffeurRepository' => ['privates', 'App\\Repository\\ChauffeurRepository', 'getChauffeurRepositoryService', true],
            'infotrafficRepository' => ['privates', 'App\\Repository\\InfotraficRepository', 'getInfotraficRepositoryService', true],
        ], [
            'chauffeurRepository' => 'App\\Repository\\ChauffeurRepository',
            'infotrafficRepository' => 'App\\Repository\\InfotraficRepository',
        ]);
    }
}
