<?php

namespace ContainerXgjGAzv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfotraficService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TDmlSVs.App\Entity\Infotrafic' shared service.
     *
     * @return \App\Entity\Infotrafic
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TDmlSVs": it references class "App\\Entity\\Infotrafic" but no such service exists.');
    }
}
