<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chauffeur extends \App\Entity\Chauffeur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'nomc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'prenomc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'numc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'adressec', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'emailc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'infotrafic'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'nomc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'prenomc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'numc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'adressec', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'emailc', '' . "\0" . 'App\\Entity\\Chauffeur' . "\0" . 'infotrafic'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chauffeur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomc', []);

        return parent::getNomc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomc(string $nomc): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomc', [$nomc]);

        return parent::setNomc($nomc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomc', []);

        return parent::getPrenomc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomc(string $prenomc): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomc', [$prenomc]);

        return parent::setPrenomc($prenomc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumc(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumc', []);

        return parent::getNumc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumc(int $numc): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumc', [$numc]);

        return parent::setNumc($numc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressec(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressec', []);

        return parent::getAdressec();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressec(string $adressec): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressec', [$adressec]);

        return parent::setAdressec($adressec);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailc', []);

        return parent::getEmailc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailc(string $emailc): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailc', [$emailc]);

        return parent::setEmailc($emailc);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfotrafic(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfotrafic', []);

        return parent::getInfotrafic();
    }

    /**
     * {@inheritDoc}
     */
    public function addInfotrafic(\App\Entity\Infotrafic $infotrafic): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInfotrafic', [$infotrafic]);

        return parent::addInfotrafic($infotrafic);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInfotrafic(\App\Entity\Infotrafic $infotrafic): \App\Entity\Chauffeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInfotrafic', [$infotrafic]);

        return parent::removeInfotrafic($infotrafic);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
